# Generated by Django 4.2.2 on 2023-06-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('action_type', models.CharField(choices=[('visit', 'Visit'), ('purchase', 'Purchase')], max_length=10)),
                ('page_id', models.IntegerField(null=True)),
                ('purchased_items', models.TextField(null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.site')),
            ],
        ),
    ]
